name: CI build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: |
        cd vue
        npm install
        npm run build
    - run: |
        python -m venv venv
        venv\Scripts\activate.ps1
        pip install -r requirements.txt
        pyinstaller --noconfirm --onefile --windowed --icon "./web/favicon.ico" --add-data "./module/*.exe;./module/" --add-data "./web;web/" --additional-hooks-dir=".\\hooks" "./main_devnull.py" --name "NsEmuTools"
        pyinstaller --noconfirm --onefile --console --icon "./web/favicon.ico" --add-data "./module/*.exe;./module/" --add-data "./web;web/" --additional-hooks-dir=".\\hooks" "./main.py" --name "NsEmuTools-console"
#        pip install pywebview
#        pyinstaller --noconfirm --onefile --console --icon "./web/favicon.ico" --add-data "./module/*.exe;./module/" --add-data "./web;web/" --additional-hooks-dir=".\\hooks" "./ui_webview.py" --name "NsEmuTools-webview"
    - uses: actions/upload-artifact@v3
      with:
        path: dist/NsEmuTools.exe
        name: NsEmuTools
    - uses: actions/upload-artifact@v3
      with:
        path: dist/NsEmuTools-console.exe
        name: NsEmuTools-console
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: false
        token: ${{secrets.token}}
        files: |
          dist/*.exe
